### ISSUE TITLE
Backend to Express

### ISSUE THREAD

**Issue by Laoujin** [be-pongit/confac-front#94]
* [x] Update README
* [x] Away with Mongoose
* [x] Test everything

**Comment by Laoujin** [comment]
@jsefiani : Lijst ELKE frontend actie die je getest hebt hier op.

**Comment by jsefiani** [comment]
1. dsdsds

**Comment by jsefiani** [comment]
Dit is allemaal getest geweest:

**Invoices page:**
- Get all invoices
- Download invoice PDF
- View invoice PDF in browser
- Verify invoice
- Delete invoice
- Download CSV file with all visible invoices
- Download Zip with all visible invoices

**Invoice page (edit mode):**
- Edit invoice
- View invoice PDF in browser
- Preview invoice PDF in browser of current data
- Download invoice PDF
- Send email with attachment when Sendgrid API key is set and sender is configured in config otherwise display correct error
- Add/delete/view/download attachment
- Add and use new client
- Edit client in modal
- Verify invoice

**Invoice page (create mode):**
- Create invoice when invoice number and date is higher than the last added invoice's number and date otherwise display correct error
- Preview invoice PDF in browser of current data
- Add and use new client

**Clients page:**
- Get all clients
- Activate/deactivate client

**Client (create mode):**
- Validate VAT
- Create client

**Client (edit mode):**
- Edit client
- Validate VAT
- Add/delete/download/view attachment

**Projects page:**
- Get all projects
- Deactivate project (UI not updated properly while "active" prop is set to false)

**Project page (edit mode):**
- Edit project
- Add and use new consultant
- Use one of existing consultants to update project

**Project page (create mode):**
- Create project
- Add and use new consultant
- Use one of existing consultants to create project

**Config:**
- Create config
- Edit config
	- Configure standard client
	- Configure standard invoice attachments
	- Configure invoice email

**Project month:**
- Create project month
- Add note
- Edit project month
	- Add amount of days/hours as on the timesheet attachment
	- Add amount of days/hours as on report from social secretary timesheet
	- Verify/refute timesheet
	- Add note to timesheet
	- Add inbound invoice number
	- Add date when received inbound invoice number
	- Verify timesheet by changing status to "validated"
	- Verify whether invoice is paid by changing status to "paid"
	- Create/verify/download/view/delete invoice
	- Add note to project

Enkel de offerte functionaliteit, maar dat volgt nog.

**Comment by jsefiani** [comment]
Nieuwe testen:

Branches:
feature/templateQuotation (FE and BE)

**Quotations page:**
- Get all quotes
- Delete quote
- Download quote PDF
- View quote PDF in browser

**Quote page (edit mode):**
- Edit quote
- View quote PDF in browser
- Preview quote PDF in browser of current data
- Download quote PDF
- Send email with attachment when Sendgrid API key is set and sender is configured in config otherwise display correct error
- Add/delete/view/download attachment
- Add and use new client
- Edit client in modal

**Quote page (create mode):**
- Create quote (same quote number allowed)
- Preview invoice PDF in browser of current data
- Add and use new client

**Comment by Laoujin** [comment]
Validate VAT: Does not work
